### ISSUE TITLE
Argon2 KeyLength support (minor)

### ISSUE THREAD

**Issue by james-d-elliott** [simia-tech/crypt#3]
Love the module/library. Was hoping you'd consider supporting the Key Length being an optional configuration variable? It's not a highly important change but it would be a nice quality of life one. I'd be happy to do a PR if desired.

**Comment by phifty** [comment]
Hi James, great that you find the lib useful. I've added the key size as parameter `k` to the `argon2i` and `argon2id` hashing. Enjoy!

**Comment by james-d-elliott** [comment]
Wow, thanks for the quick release. Just noticed this bug (note the Argon2i values instead of Argon2id):

https://github.com/simia-tech/crypt/blob/master/argon2id.go#L82-L96

**Comment by phifty** [comment]
Always up for some progress ;-) Good bug spotting. Pushed a new release.

**Comment by james-d-elliott** [comment]
Nice, working well! Thanks again.
